name: letschat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.4
  pinput: ^0.2.6
  flutter_search_bar: ^2.1.0
  fab_circular_menu: ^1.0.0
  firebase_storage: ^5.2.0
  firebase_image: ^0.3.0
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+17
  floating_action_bubble: 1.0.9
  cached_network_image: ^2.4.1
  loading: ^1.0.2
  adaptive_action_sheet: ^1.0.9
  esys_flutter_share: ^1.0.2
  cupertino_icons: ^0.1.3
  gallery_saver: ^2.0.1
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2
  image: ^2.1.19
  contacts_service: ^0.4.6
  file_picker: ^1.4.0+1
  emoji_picker: ^0.1.0
  video_player: ^0.10.2+1
  flutter_downloader: ^1.2.2
  downloads_path_provider: ^0.1.0
  dio: ^3.0.0
  path_provider: ^1.3.0
  file_utils: ^0.1.3
  permission_handler: ^5.0.1+1
  country_code_picker: ^1.7.0
  flutter_bloc: ^7.0.0
  bloc: ^7.1.0
  rxdart: ^0.25.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - images/
